### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by bawet27** [Kannachann/KannaBOT-MD#1]
ini menu kok gabisa bang
![Screenshot_2022-04-22-16-05-10-97](https://user-images.githubusercontent.com/98907223/164674681-1545e04f-ef81-4963-8e8d-adbfcc0fafc2.jpg)

**Comment by Kannachann** [comment]
idk :v

**Comment by Kannachann** [comment]
udh di fix yy

**Comment by Kangsad01** [comment]
> ini menu kok gabisa bang ![Screenshot_2022-04-22-16-05-10-97](https://user-images.githubusercontent.com/98907223/164674681-1545e04f-ef81-4963-8e8d-adbfcc0fafc2.jpg)

Udh set public ?
